include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    invalid_override: error
    dead_code: warning
    overridden_fields: ignore
    always_specify_types: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    avoid_empty_else: true
    avoid_print: true
    avoid_returning_null: true
    avoid_relative_lib_imports: true
    avoid_single_cascade_in_expression_statements: true
    curly_braces_in_flow_control_structures: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_null_aware_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    avoid_void_async: true
    type_init_formals: true
    unnecessary_overrides: true
    unnecessary_nullable_for_final_variable_declarations: true
    prefer_typing_uninitialized_variables: true
    prefer_interpolation_to_compose_strings: true
    prefer_adjacent_string_concatenation: true
    always_use_package_imports: true
    library_prefixes: true
    use_build_context_synchronously: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    use_named_constants: true
    use_rethrow_when_possible: true
    use_super_parameters: true
    null_check_on_nullable_type_parameter: true
    unnecessary_null_checks: true
    always_specify_types: true
