name: currex
description: "—Åurrency exchange app"
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  # Core
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  crypto: ^3.0.6
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Storage
  flutter_secure_storage: ^9.2.4

  # Network
  dio: ^5.8.0+1

  # Routing
  auto_route: ^10.0.1

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # UI
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.4
  freezed: ^3.0.4

flutter:
  uses-material-design: true
